config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  get 'page/contact'

  get 'page/about'

  post 'page/sendEmail'

  resources :products, only: [:index, :show] do
    resources :likes
    resources :comments
  end  

  resources :charges, only: [:new,:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_type
	has_many :likes, dependent: :nullify
	has_many :comments, dependent: :nullify	

	validates :name, presence: true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
	has_many :products
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
include Clearance::User

  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = ((params[:price].to_f)*100).to_i
	  @price  = params[:price]
	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :lookup_project

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
    format.html {redirect_to @comment}
    format.js {} #automatically call destroy.js.erb , because it calls by default the name of the method
    end 
  end

  def create 
  	@comment = @product.comments.new(comment_params)
  	@comment.save    
    respond_to do |format|
      format.html { redirect_to @comment}
      format.js {}
    end
  end	

  def lookup_project
  	@product = Product.find(params[:product_id])
  end	

  def comment_params
  	params.require(:comment).permit(:body,:product_id)
  end	


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :lookup_project

	def create
    @like = Like.new
    @like.product = @product
    @like.save
      respond_to do |format|
      format.html { redirect_to root_url }
      format.js {}
    end  
  end

  def lookup_project
 		@product = Product.find(params[:product_id])
  end	

end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
  end

  def contact
    @current ||= current_user
  end	

	def about
	end	
	
  def sendEmail
  	redirect_to root_path , notice: contact_params[:email]
  end

private

def contact_params
	params.require(:page).permit(:name, :email, :message)
end	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end	

	def show
		@product = Product.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @price %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/comments/_comment.html.erb
<%= form_for [product, product.comments.new], remote: true do |f| %>
  <%= f.text_field :body, required: true, placeholder: 'Add a comment' %>
  <%= f.submit 'Save' %>
<% end %>

<div class = 'comments' id='product-<%= product.id %>-comments'>

<% product.comments.order('created_at DESC').each do |commentarios| %>
	<%= link_to 'Mark as Spam', product_comment_path(commentarios.product.id, commentarios.id) , method: :delete ,remote: true, id: 'remove_comment_' + commentarios.id.to_s, data: { confirm: "Are you sure?" 	} %>

<p id="comment_<%= commentarios.id %>"> 
		<%= commentarios.body%>
		<div class = 'comments_created_at' id= "comment_<%= commentarios.id %>_created_at" ><p>Created at: <%= commentarios.created_at %></p>
		</div>
</p>

<% end %>

</div>

app/views/comments/create.js.erb
$('#product-<%= @comment.product.id %>-comments').prepend('<p id="comment_<%= @comment.id %>"> <%= @comment.body %> <div class = "comments_created_at" id = "comment_<%= @comment.id %>_created_at"> <%= @comment.created_at %></div> </p>');

$('#product-<%= @comment.product.id %>-comments').prepend("<%= escape_javascript(link_to 'Mark as Spam', product_comment_path(@comment.product.id, @comment.id) , method: :delete ,remote: true, id: 'remove_comment_' + @comment.id.to_s, data: { confirm: 'Are you sure?' 	} ) %>");

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').detach();
$('#remove_comment_<%= @comment.id %>').detach();
$('#comment_<%= @comment.id%>_created_at').detach();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Link to Jquery-->
  <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>

  <!-- Link to SlideMe css -->
  <%= stylesheet_link_tag 'slideme', 'data-turbolinks-track' => true %>

  <!-- Link to css file for smartmenu css file-->
  <%= stylesheet_link_tag 'sm-core-css' ,'data-turbolinks-track' => true %>

  <!-- Link for css for jqueryui -->
  <%= stylesheet_link_tag 'jquery-ui.structure.css' ,'data-turbolinks-track' => true %>

  <!-- -->
  <%= stylesheet_link_tag 'jquery-ui.theme.min.css', 'data-turbolinks-track' => true %>

  <!-- Link For Slideme PlugIn -->
  <%= javascript_include_tag 'jquery.slideme-1.21.71.js' ,'data-turbolinks-track' => true %>

  <!-- Link For  SmartMenu PlugIn-->
  <%= javascript_include_tag 'jquery.smartmenus.js' ,'data-turbolinks-track' => true %>

  <!-- Link For JqueryUI PlugIn-->
  <%= javascript_include_tag 'jquery-ui', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <div id= "signed"> 
      <% if signed_in? %>
        <p>Signed in as: <%= current_user.email %></p>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% end %>
    </div>  
  <ul id="main-menu" class="sm sm-blue">
    <li><%= link_to 'Home', root_path, id: 'home-link' %></li>
    <li><%= link_to 'Products', products_path , id: 'products-link' %></li>
    <li><%= link_to 'Contact', page_contact_path , id: 'contact-link' %></li>
    <li><%= link_to 'About', page_about_path , id: 'about-link' %></li>
    <li> <%= link_to 'Sign in', sign_in_path, id:'sign-in' %> </li>
    <li> <%= link_to 'Sign up', sign_up_path, id:'sign-up' %> </li>
  </ul>

  </header>

<%= yield %>

  <footer>
    <p>Tel: 250-234-0456</p>
    <p> 5th Street, Courtenay, BC</p>
  </footer>

</body>
</html>

app/views/likes/create.js.erb
$('#likes_<%=@like.product.id%>').replaceWith( "<p id='likes_<%=@like.product.id%>'> <%= @like.product.likes.count %> </p>");

app/views/page/about.html.erb
<div id="accordion">
  <h3>Section 1</h3>
  <div>
    <p>Mauris mauris ante, blandit et, ultrices a, susceros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
  </div>
  <h3>Section 2</h3>
  <div>
    <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna. </p>
  </div>
  <h3>Section 3</h3>
  <div>
    <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui. </p>
    <ul>
      <li>List item</li>
      <li>List item</li>
      <li>List item</li>
      <li>List item</li>
      <li>List item</li>
      <li>List item</li>
      <li>List item</li>
    </ul>
  </div>
</div>

  <script>
  $(function() {
    $( "#accordion" ).accordion({
      heightStyle: "content"
    });
  });
  </script>

app/views/page/contact.html.erb
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script > 
      function initialize() {
        var mapProp = {
        center:new google.maps.LatLng(49.6841391,-124.990449300000020000),
        zoom:13,
        mapTypeId:google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
      }

      google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="googleMap" style="width: 500px; height: 380px;"></div>

<div id= "address">
  <p>Tel: 250-234-0456</p>
  <p> 5th Street, Courtenay, BC</p>
</div>

<div id='contact-form'>
  <%= form_tag('sendEmail') do %>
    <%= label_tag :name %><br/>
    <%= text_field :page, :name %>

    <br><br>

    <%= label_tag :email %><br/>
    <% if signed_in? %>
      <%= text_field :page, :email , value:  @current.email %>
    <% else %>
      <%= text_field :page, :email %>
    <% end %>
    <br><br>

    <%= label_tag :message %><br/>
    <%= text_field :page, :messsage %>

    <br><br>

    <%= submit_tag 'Send' %>
  <% end %>
</div>

app/views/page/index.html.erb
<div id='foo'>

	<ul class='slideme'>
		<li><%= image_tag 'natura01.jpg' ,  alt: "Products Natura" %></li>
		<li><%= image_tag 'nature.jpeg'%></li>
	</ul>

</div>

<script >
	$(function() { 
		$('#foo').slideme({
		autoslide : true,
		interval : 2500,
		loop : true,
		});
	});	
</script>

app/views/products/_product.html.erb
<div class='partial-Product'>
	<%= link_to (image_tag (product.name+'.jpg')) , product_path(product) %>
	<p>Name: <%= product.name %></p>
	<p>Price: <%= product.price %></p>

</div>

app/views/products/index.html.erb
<div id="products">
	<%= render(partial: "product", collection: @products ) %>
</div>

app/views/products/show.html.erb
<%= image_tag @product.name + '.jpg' , class: 'image-show' %>

<p><%= @product.name %></p>
<p><%= @product.price %></p>
<p><%= @product.description %></p>

<%= form_tag charges_path do %>
	<%= hidden_field_tag(:price, @product.price) %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount= <%= (@product.price.to_f) * 100 %>  > </script>
<% end %>

<div class = 'likes-products'> 
    <div class='form-like-product'> 
  	 <%= form_for [@product,Like.new] , remote: true do |f| %>
      <%= f.hidden_field :product, value: @product %>
      <%= f.submit 'like' %>
  	 <% end %>
    </div>
  <p id='likes_<%= @product.id%>'><%= @product.likes.count %></p> 
</div>

<%= render "comments/comment", product: @product %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %> <br/>
  <%= form.text_field :email, type: 'email' %>
</div>
<br>
<div class="password-field">
  <%= form.label :password %><br/>
  <%= form.password_field :password %>
</div>
<br/>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    
    <div class="submit-field">
      <%= form.submit %>
    </div>
    <br/>
    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>